import type { Redaction, RedactionPart, BoundingBox, HighlightInProgress, PageData, WordData } from '@/types'

export function generateUUID(): string {
  return crypto.randomUUID()
}

export function boundingBox(redaction: Redaction): BoundingBox {
  const xs0 = redaction.parts.map(p => p.x)
  const ys0 = redaction.parts.map(p => p.y)
  const xs1 = redaction.parts.map(p => p.x + p.width)
  const ys1 = redaction.parts.map(p => p.y + p.height)
  return { x0: Math.min(...xs0), y0: Math.min(...ys0), x1: Math.max(...xs1), y1: Math.max(...ys1) }
}

export function quadToPart(quad: number[]): RedactionPart {
  const [x0, y0, x1, y1, x2, y2, x3, y3] = quad
  const x = Math.min(x0, x1, x2, x3)
  const y = Math.min(y0, y1, y2, y3)
  return { x, y, width: Math.max(x0, x1, x2, x3) - x, height: Math.max(y0, y1, y2, y3) - y }
}

/**
 * Editor-like caret hit-test at word granularity.
 * Returns a caret index in [0, words.length]: the position *between* words
 * (in reading order) closest to the given point. Vertical distance dominates,
 * so clicking in the margin snaps to the nearest line, like in a text editor.
 */
export function caretIndexAt(words: WordData[], x: number, y: number): number {
  if (!words.length) return 0
  let best = 0
  let bestScore = Infinity
  for (let i = 0; i < words.length; i++) {
    const b = words[i].bbox
    const dy = y < b.y0 ? b.y0 - y : y > b.y1 ? y - b.y1 : 0
    const dx = x < b.x0 ? b.x0 - x : x > b.x1 ? x - b.x1 : 0
    const score = dy * 100 + dx
    if (score < bestScore) { bestScore = score; best = i }
  }
  const b = words[best].bbox
  return x > (b.x0 + b.x1) / 2 ? best + 1 : best
}

/** True if two word bboxes sit on the same visual line (>50% vertical overlap). */
function sameLine(a: BoundingBox, b: BoundingBox): boolean {
  const overlap = Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0)
  return overlap > 0.5 * Math.min(a.y1 - a.y0, b.y1 - b.y0)
}

export function finalizeHighlight(page: PageData, highlight: HighlightInProgress): Redaction {
  if (highlight.type === 'freehand') {
    const x = Math.min(highlight.startX, highlight.endX)
    const y = Math.min(highlight.startY, highlight.endY)
    return {
      id: generateUUID(), documentKey: '', pageIndex: highlight.pageIndex,
      parts: [{ x, y, width: Math.abs(highlight.endX - highlight.startX), height: Math.abs(highlight.endY - highlight.startY) }],
      status: 'manual', shouldApply: true, isAutoGenerated: false,
    }
  }

  // Text selection: all words between the two carets, one rect per visual line
  const a = highlight.startWordIndex ?? 0
  const b = highlight.endWordIndex ?? 0
  const selected = page.words.slice(Math.min(a, b), Math.max(a, b))

  const parts: RedactionPart[] = []
  let cur: BoundingBox | null = null
  for (const w of selected) {
    if (cur && sameLine(cur, w.bbox) && w.bbox.x0 >= cur.x0) {
      cur.x1 = Math.max(cur.x1, w.bbox.x1)
      cur.y0 = Math.min(cur.y0, w.bbox.y0)
      cur.y1 = Math.max(cur.y1, w.bbox.y1)
    } else {
      if (cur) parts.push({ x: cur.x0, y: cur.y0, width: cur.x1 - cur.x0, height: cur.y1 - cur.y0 })
      cur = { ...w.bbox }
    }
  }
  if (cur) parts.push({ x: cur.x0, y: cur.y0, width: cur.x1 - cur.x0, height: cur.y1 - cur.y0 })

  return { id: generateUUID(), documentKey: '', pageIndex: highlight.pageIndex, parts, status: 'manual', shouldApply: true, isAutoGenerated: false }
}

export function redactionsToAnnotations(redactions: Redaction[]) {
  return redactions.filter(r => r.status !== 'ignored' && r.shouldApply !== false).map(r => ({
    content: r.rule?.title || '',
    position: {
      pageNumber: r.pageIndex,
      rect: [r.parts[0].x, r.parts[0].y, r.parts[0].x + r.parts[0].width, r.parts[0].y + r.parts[0].height],
      quads: r.parts.map(p => [p.x, p.y, p.x + p.width, p.y, p.x, p.y + p.height, p.x + p.width, p.y + p.height]),
    },
  }))
}

const overlaps = (w: { bbox: { x0: number; y0: number; x1: number; y1: number } }, r: { x: number; y: number; width: number; height: number }) => {
  const cy = (w.bbox.y0 + w.bbox.y1) / 2
  return w.bbox.x1 >= r.x && w.bbox.x0 <= r.x + r.width && cy >= r.y && cy <= r.y + r.height
}

export function getRedactionText(redaction: Redaction, page: PageData): string {
  const words = [...page.words].sort((a, b) => {
    const dy = a.bbox.y0 - b.bbox.y0
    return Math.abs(dy) > 5 ? dy : a.bbox.x0 - b.bbox.x0
  })
  return words
    .filter(w => redaction.parts.some(p => overlaps(w, p)))
    .map(w => w.text)
    .join(' ')
}
