stages:
  - sync

mirror-to-github:
  stage: sync
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/alpine/git:latest
  tags:
    - generic
  variables:
    GIT_STRATEGY: clone
    GIT_CHECKOUT: "false"
  script:
    - git remote add github https://x-access-token:${GITHUB_PAT}@github.com/datenlabor-bmz/easy-redact.git
    - git push github --all --force
    - git push github --tags --force
