// ── PDF / redaction geometry ──────────────────────────────────────────────────

export interface RedactionPart {
  x: number
  y: number
  width: number
  height: number
}

export interface BoundingBox {
  x0: number; y0: number; x1: number; y1: number
}

export interface WordData {
  text: string
  bbox: BoundingBox
}

export interface PageData {
  image: string
  bounds: [number, number, number, number]
  content: any
  lines: any[]
  words: WordData[]
}

export interface HighlightInProgress {
  pageIndex: number
  type: 'freehand' | 'text'
  startX: number; startY: number; endX: number; endY: number
  startWord: WordData | null; endWord: WordData | null
}

// ── Rules ─────────────────────────────────────────────────────────────────────

export interface RedactionRule {
  group?: string
  title: string
  reference?: string
  reason?: string
  full_text?: string
  url?: string
}

export interface JurisdictionMeta {
  id: string
  jurisdiction: string
  jurisdiction_name: string
  law_name: string
  abbreviation: string
  language: string
  url: string
}

// ── Redactions ────────────────────────────────────────────────────────────────

export type RedactionStatus = 'manual' | 'suggested' | 'accepted' | 'ignored'
export type RedactionConfidence = 'high' | 'low'

export interface Redaction {
  id: string
  documentKey: string   // idbKey of the document this redaction belongs to; stamped by App.addRedaction
  pageIndex: number
  parts: RedactionPart[]
  searchText?: string   // original search text used to locate this redaction (set for AI suggestions)
  rule?: RedactionRule
  status: RedactionStatus
  confidence?: RedactionConfidence
  person?: string       // e.g. "Max Mustermann"
  personGroup?: string  // e.g. "Bürger", "Beamte", "Personen im BMZ"
  reason?: string
  shouldApply?: boolean // for mupdf export compat
  isAutoGenerated?: boolean
  isIndeterminate?: boolean
}

export interface RedactionSuggestion {
  text: string          // search text to locate in PDF
  pageIndex: number
  confidence: RedactionConfidence
  person?: string
  personGroup?: string
  rule?: RedactionRule
  reason?: string
}

// ── Session ───────────────────────────────────────────────────────────────────

export type ConsentMode = 'cloud' | 'local' | null
export type RedactionMode = 'pii' | 'foi'

export interface DocumentMeta {
  name: string
  idbKey: string
  pageCount?: number
}

export interface Session {
  id: string
  documents: DocumentMeta[]
  redactions: Redaction[]
  consent: ConsentMode
  redactionMode: RedactionMode
  foiJurisdiction?: string
  modelSettings: {
    cloudDeployment: string
    localBase: string
    localModel: string
  }
}

// ── Chat ──────────────────────────────────────────────────────────────────────

export interface ToolCall {
  id: string
  name: string
  args: Record<string, unknown>
  result?: unknown
  success?: boolean
  status: 'pending' | 'running' | 'complete' | 'error'
}

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  toolCalls?: ToolCall[]
  timestamp: string  // ISO string for serialization
  hidden?: boolean   // silent context messages not rendered in UI
  question?: AskUserQuestion
  consentRequired?: string  // reason string when AI requested document access
}

export interface AskUserOption {
  id: string
  label: string
}

export interface AskUserQuestion {
  question: string
  options: AskUserOption[]
  allowFreeform: boolean
  answered?: boolean
}

// ── SSE event types ───────────────────────────────────────────────────────────

export type SSEEvent =
  | { type: 'tool_start'; id: string; name: string; args: Record<string, unknown> }
  | { type: 'tool_result'; name: string; result: unknown; success: boolean }
  | { type: 'text_delta'; content: string }
  | { type: 'consent_required'; reason: string }
  | { type: 'ask_user'; question: AskUserQuestion }
  | { type: 'suggest_redactions'; suggestions: RedactionSuggestion[]; remove: string[] }
  | { type: 'done' }
  | { type: 'error'; message: string }

// ── Chat API request ──────────────────────────────────────────────────────────

export interface ApiChatMessage {
  role: 'user' | 'assistant' | 'system' | 'tool'
  content: string
  tool_call_id?: string
  tool_calls?: Array<{
    id: string
    type: 'function'
    function: { name: string; arguments: string }
  }>
}

export interface RedactionSnapshot {
  id: string
  status: RedactionStatus
  pageIndex: number
  text: string
  person?: string
  personGroup?: string
  documentKey: string
}

export interface ChatRequest {
  messages: ApiChatMessage[]
  model: 'cloud' | 'local'
  consent: ConsentMode
  redactionMode: RedactionMode
  foiJurisdiction?: string
  documentPages?: Array<{ pageIndex: number; text: string }>
  currentRedactions?: RedactionSnapshot[]
}
